baseurl = ""
title = ""
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
  author = "Timm Heuss"
  info = "Problem Solver, Software Craftsman, Computer Science Nerd"
  description = "John Doe's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "https://avatars.githubusercontent.com/u/887095?v=4"
  #gravatar = "john.doe@example.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  footercontent = "Enter a text here."
  hideFooter = true
  hideCredits = false
  hideCopyright = false
  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/heussd/"
[[params.social]]
  name = "Docker"
  icon = "fab fa-docker fa-2x"
  weight = 1
  url = "https://hub.docker.com/r/heussd/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/heuss"
[[params.social]]
  name = "Xing"
  icon = "fa fa-xing fa-2x"
  weight = 2
  url = "https://www.xing.com/profile/Timm_Heuss/"


# Menu links
#[[menu.main]]
#  name = "Blog"
#  weight = 1
#  url  = "posts/"
#[[menu.main]]
#  name = "About"
#  weight = 2
#  url = "about/"